### ISSUE TITLE
Outputs images look strange

### ISSUE THREAD

**Issue by andrewginns** [LynnHo/CycleGAN-Tensorflow-Simple#5] opened 2018-03-20 11:30 UTC
I'm utilising the Adobe-MIT dataset to try and train the network to learn a professional editing style. Training set A is original unedited images, training set B is edited images. Images are all 8bit jpg files.

The outputs I get from the trained network using test.py look strange, wondering if anyone has insight.

![a5000-kme_0204](https://user-images.githubusercontent.com/25386449/37651895-93478c10-2c31-11e8-9681-7dfa58334988.jpg)
![a4876-dsc_0043-2](https://user-images.githubusercontent.com/25386449/37651903-987d9efe-2c31-11e8-9859-1a267370c779.jpg)
![a4718-_dgw9472](https://user-images.githubusercontent.com/25386449/37652071-2571d2da-2c32-11e8-8bc4-015e91a30f2b.jpg)

The network seems to have learnt to invert part or all of the image. Could this be due to an overflow somewhere?

For these examples the network was trained on paired data, though I can't imagine that would have caused problems. Everything else is default.

**Comment by LynnHo** [comment] 2018-03-20 11:47
@andrewginns Can you post one image of training set A and one of training set B?

**Comment by andrewginns** [comment] 2018-03-20 12:05
@LynnHo 
Training set A image:
![a2100-_dsc3268](https://user-images.githubusercontent.com/25386449/37653489-013d7c70-2c37-11e8-8013-ca2a010d99d8.jpg)

Training set B image:
![a2100-_dsc3268-2](https://user-images.githubusercontent.com/25386449/37653488-01244f3e-2c37-11e8-965b-cc91d50e9980.jpg)

**Comment by LynnHo** [comment] 2018-03-20 12:16
@andrewginns It's strange indeed. Actually I have met the situation that the transferred image looks like the X-ray image (the third row). At such situation, restarting the training may fix the problem. I guess it's caused by the random initialization - a "bad" initialization result in such situation.

**Comment by andrewginns** [comment] 2018-03-20 12:25
@LynnHo I see, would looking at the 'sample images while training' outputs help me catch the problem earlier? I notice that the x-ray effect occurs in almost all of my early epoch outputs

**Comment by LynnHo** [comment] 2018-03-20 12:38
@andrewginns In my experience, the training should be stopped if there is such phenomenon at early epochs, at least it works on the horse2zebra dataset.

**Comment by andrewginns** [comment] 2018-03-20 12:43
@LynnHo thanks. I'll see if I can retrain and catch it if it happens again. Fingers crossed that's the issue

**Closed as completed** 2018-03-20 12:43 UTC

**Comment by asif31iqbal** [comment] 2018-11-06 18:52
@andrewginns Were you able to get around the problem by using a different weight initialization?
I am getting the same problem with horse2zebra images. The zebra-horse-zebra stuff is working fine, but in the horse-zebra-horse cycle, the fake zebra looks like an x-ray image. @LynnHo 
![epoch_ 199 _ 1000of1067](https://user-images.githubusercontent.com/4718929/48086546-1adb7200-e1cb-11e8-9ecb-b8f3911dda6d.jpg)

**Comment by andrewginns** [comment] 2018-11-06 19:07
I solved it by using a known model that was known to be good after ~50 epochs as a base. Put known good pre-trained .ckpt's into your checkpoints folder and start the new dataset training from there. The x-ray effect seems to be caused by some convergence to local minima in early training stages.

Strange that your A-B-A translation works but your B-A-B doesn't.

**Comment by asif31iqbal** [comment] 2018-11-06 20:11
@andrewginns Do you have any link for a good PyTorch checkpoint for this?

**Comment by andrewginns** [comment] 2018-11-06 20:21
@asif31iqbal

I don't unfortunately, all my training checkpoints are in tensorflow graphdef format

**Comment by asif31iqbal** [comment] 2018-11-06 20:25
No Problem. Thanks for the help and suggestion.
